name = "onedrive-cloudflare-index"
main = ".open-next/worker.js"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "onedrive-cloudflare-index"

[[kv_namespaces]]
binding = "CLOUDFLARE_KV"
id = "replace-with-production-kv-namespace-id"
preview_id = "replace-with-preview-kv-namespace-id"
